/** @layer core */
// Writes the BeamNG level's config + asset files into the archive recorder:
// folder skeleton, info.json, mainLevel.lua, preview.png, export_report.txt,
// the Road Architect session, theTerrain.ter + heightmap, art/shapes (OSM /
// junction / backdrop / Google-tiles DAEs + their main.materials.json), the
// art/terrains terrain.png + PBR textures + material defs, and the route-mode
// per-chunk tile folders. Pure: takes every artifact via `ctx` so it imports no
// io/renderer/?raw modules and runs headless. Extracted verbatim from
// exportBeamNGLevel.js (06 step 9b).
import { buildMainLevelLua } from './levelLua.js';
import { EAST_COAST_FENCE_MATERIAL_DEFS } from './barriers.js';

/**
 * Write the level's files (everything except the main/MissionGroup/* scene tree,
 * which writeMissionGroup handles) into the `zip` recorder.
 */
export function writeLevelFiles(zip, ctx) {
  const {
    levelName, levelDisplayName, lat, lng, size,
    terBlob, roadArchitectSession, roadArchitectHeightmapBlob,
    osmDaeBlob, junctionsDaeBlob, backdropDaeBlob, backdropTextureFiles,
    googleTilesGlbBlob, googleTilesDaeBlob, googleTilesTextureFiles, googleDebugCubeBlob,
    mapngFlagFiles, shapeMaterialDefsForFlavor, usesEastCoastFenceMaterials,
    groundCoverObjects, groundCoverProfile, forestFiles, barrierFolderItems,
    roadFolderGroups, meshRoads, pbrResult, routeTilePieces, reportContents,
    beamngGlbToDaeScript,
  } = ctx;
  // previewBlob/heightmapBlob/texBlob are nulled after writing (memory hygiene
  // carried over verbatim), so they need mutable bindings.
  let { previewBlob, heightmapBlob, texBlob } = ctx;
  const base = `levels/${levelName}`;

  // Explicit directory entries so BeamNG's FS:directoryExists() works correctly
  zip.folder('levels');
  zip.folder(base);
  zip.folder(`${base}/art`);
  zip.folder(`${base}/bat`);
  zip.folder(`${base}/art/terrains`);
  zip.folder(`${base}/main`);
  zip.folder(`${base}/main/MissionGroup`);
  zip.folder(`${base}/main/MissionGroup/Level_objects`);
  zip.folder(`${base}/main/MissionGroup/Level_objects/Other`);
  zip.folder(`${base}/main/MissionGroup/PlayerDropPoints`);
  zip.folder(`${base}/main/MissionGroup/Water`);
  if (barrierFolderItems.length > 0) {
    zip.folder(`${base}/main/MissionGroup/barriers`);
  }
  if (roadFolderGroups.length > 0) {
    zip.folder(`${base}/main/MissionGroup/roads`);
  }
  if (meshRoads.length > 0) {
    zip.folder(`${base}/main/MissionGroup/Mesh_roads`);
  }
  if (forestFiles.length > 0 || groundCoverObjects.length > 0) {
    zip.folder(`${base}/main/MissionGroup/Level_objects/vegetation`);
    zip.folder(`${base}/art/forest`);
    zip.folder(`${base}/forest`);
  }

  // ── info.json ──────────────────────────────────────────────────────────────
  zip.file(`${base}/info.json`, JSON.stringify({
    authors: 'mapng',
    defaultSpawnPointName: 'spawn_default',
    description: `Generated by mapng at ${lat}, ${lng}`,
    previews: ['preview.png'],
    size: [size, size],
    spawnPoints: [{
      name: 'Default',
      objectname: 'spawn_default',
      preview: 'preview.png',
      translationId: 'Default Spawnpoint',
    }],
    title: levelDisplayName,
  }, null, 2));

  // ── mainLevel.lua ──────────────────────────────────────────────────────────
  // Lua initialization script executed on level load. Expected by BeamNG's
  // level subsystem and the World Editor.
  zip.file(`${base}/mainLevel.lua`, buildMainLevelLua());

  // ── preview.png ────────────────────────────────────────────────────────────
  zip.file(`${base}/preview.png`, previewBlob);
  previewBlob = null;

  zip.file(`${base}/export_report.txt`, reportContents);

  if (roadArchitectSession) {
    zip.file(`${base}/bat/roadatchitectsession.json`, JSON.stringify(roadArchitectSession, null, 2));
    if (roadArchitectHeightmapBlob) {
      zip.file(`${base}/bat/roadatchitectsession.png`, roadArchitectHeightmapBlob);
    }
  }

  // ── theTerrain.ter ─────────────────────────────────────────────────────────
  zip.file(`${base}/theTerrain.ter`, terBlob);

  // ── theTerrain.terrainheightmap.png ────────────────────────────────────────
  // Grayscale heightmap preview used by BeamNG's terrain system and World Editor.
  // Capped at 2048px — the .ter binary holds the full-res data; this is display only.
  zip.file(`${base}/theTerrain.terrainheightmap.png`, heightmapBlob);
  heightmapBlob = null;

  // ── art/shapes/ (OSM 3D objects and/or terrain backdrop) ──────────────────
  // Only written when at least one DAE file is present.
  if (osmDaeBlob || junctionsDaeBlob || backdropDaeBlob || forestFiles.length > 0 || groundCoverObjects.length > 0 || mapngFlagFiles.length > 0) {
    zip.folder(`${base}/art/shapes`);
    if (mapngFlagFiles.length > 0) zip.folder(`${base}/art/shapes/mapng`);

    if (osmDaeBlob) zip.file(`${base}/art/shapes/osm_objects.dae`, osmDaeBlob);
    if (junctionsDaeBlob) zip.file(`${base}/art/shapes/road_junctions.dae`, junctionsDaeBlob);
    if (backdropDaeBlob) zip.file(`${base}/art/shapes/terrain_backdrop.dae`, backdropDaeBlob);

    // Google Photorealistic 3D Tiles live in their own folder (own
    // materials.json, own texture folder) — mirroring the working mapng_flag
    // asset layout. The geometry ships as google_tiles.glb plus a Blender
    // conversion script: BeamNG only loads .dae, and Blender's Collada
    // exporter is the BeamNG-proven serializer (see the README in the
    // folder). Run the script once, drop google_tiles.dae next to the glb.
    if (googleTilesGlbBlob) {
      zip.folder(`${base}/art/shapes/google_tiles`);
      if (googleTilesDaeBlob) {
        // The dev-server Blender bridge already produced the final shape —
        // the zip is ready to play, no GLB/conversion bundle needed.
        zip.file(`${base}/art/shapes/google_tiles/google_tiles.dae`, googleTilesDaeBlob);
      } else {
        zip.file(`${base}/art/shapes/google_tiles/google_tiles.glb`, googleTilesGlbBlob);
        zip.file(`${base}/art/shapes/google_tiles/beamng_glb_to_dae.py`, beamngGlbToDaeScript);
        zip.file(
        `${base}/art/shapes/google_tiles/README_CONVERT.txt`,
        [
          'Google 3D Tiles — one-time conversion to .dae',
          '=============================================',
          '',
          'BeamNG only loads COLLADA (.dae) shapes, and Blender\'s exporter is the',
          'reliable way to produce one.',
          '',
          '⚠ Blender 3.x or 4.x required (4.2 LTS recommended) — Collada export was',
          '  REMOVED in Blender 5.0+. A portable zip from',
          '  https://download.blender.org/release/Blender4.2/ works without installing.',
          '',
          '  1. Extract this zip (or open the folder if already extracted).',
          '  2. In this folder, run:',
          '',
          '     blender --background --factory-startup --python beamng_glb_to_dae.py -- google_tiles.glb google_tiles.dae',
          '',
          '     (On Windows, use the full path to blender.exe, e.g.',
          '      "...\\blender-4.2.9-windows-x64\\blender.exe")',
          '',
          '  3. Re-zip the level (or keep it as an unpacked folder in your BeamNG',
          '     mods directory). The level\'s items.level.json already references',
          '     google_tiles.dae — once the file exists, the photogrammetry appears.',
          '',
          'You can inspect google_tiles.glb in any glTF viewer (e.g. Blender itself,',
          'or https://gltf-viewer.donmccurdy.com) to verify the bake before converting.',
          '',
          'Textures are NOT read from the .dae — they resolve via main.materials.json',
          'in this folder (google_atlas_NN entries pointing at textures/*.png).',
        ].join('\n'),
        );
      }
      if (googleDebugCubeBlob) zip.file(`${base}/art/shapes/google_tiles/google_debug.dae`, googleDebugCubeBlob);
      // Collision mesh material (vertex-colour, no texture).
      const googleMaterials = {
        osm_object: {
          class: 'Material',
          name: 'osm_object',
          mapTo: 'osm_object',
          annotation: 'BUILDINGS',
          Stages: [{ diffuseColor: [1, 1, 1, 1], vertColor: true }],
          translucentBlendOp: 'None',
        },
      };
      // Per-tile photogrammetry textures + matching materials. Material shape
      // mirrors the working mapng_flag entry exactly (Material class uses
      // `colorMap`, not `diffuseMap`; needs 4 Stages even if 3 are empty).
      if (googleTilesTextureFiles.length > 0) {
        zip.folder(`${base}/art/shapes/google_tiles/textures`);
        for (const tex of googleTilesTextureFiles) {
          zip.file(`${base}/art/shapes/google_tiles/textures/${tex.name}.${tex.ext}`, tex.data);
          googleMaterials[tex.name] = {
            name: tex.name,
            mapTo: tex.name,
            class: 'Material',
            Stages: [
              { colorMap: `levels/${levelName}/art/shapes/google_tiles/textures/${tex.name}.${tex.ext}` },
              {},
              {},
              {},
            ],
            translucentBlendOp: 'None',
          };
        }
      }
      zip.file(`${base}/art/shapes/google_tiles/main.materials.json`, JSON.stringify(googleMaterials, null, 2));
    }
    for (const asset of mapngFlagFiles) {
      const relativePath = asset.path.startsWith('mapng/') ? asset.path.slice('mapng/'.length) : asset.path;
      if (relativePath === 'main.materials.json') {
        const materialDefs = JSON.parse(new TextDecoder().decode(asset.data));
        if (materialDefs.mapng_flag?.Stages?.[0]) {
          materialDefs.mapng_flag.class = 'Material';
          materialDefs.mapng_flag.Stages[0].colorMap = `levels/${levelName}/art/shapes/mapng/mapng_flag_d.png`;
        }
        zip.file(`${base}/art/shapes/mapng/main.materials.json`, JSON.stringify(materialDefs, null, 2));
      } else {
        zip.file(`${base}/art/shapes/mapng/${relativePath}`, asset.data);
      }
    }

    // Build a single materials JSON covering all DAEs in this directory.
    const shapeMaterials = {
      ...shapeMaterialDefsForFlavor,
      ...(usesEastCoastFenceMaterials ? EAST_COAST_FENCE_MATERIAL_DEFS : {}),
      ...(groundCoverObjects.length > 0 ? {
        [groundCoverProfile.materialName]: structuredClone(groundCoverProfile.materialDef),
      } : {}),
    };
    if (osmDaeBlob) {
      // Vertex-colour Material: BeamNG multiplies diffuseColor × vertex colour.
      // All OSM mesh materials are named "osm_object" to resolve to this entry.
      shapeMaterials.osm_object = {
        class: 'Material',
        name: 'osm_object',
        mapTo: 'osm_object',
        annotation: 'BUILDINGS',
        Stages: [{ diffuseColor: [1, 1, 1, 1], vertColor: true }],
        translucentBlendOp: 'None',
      };
    }
    if (backdropDaeBlob) {
      // Save per-tile satellite textures alongside the DAE.
      if (backdropTextureFiles.length > 0) {
        zip.folder(`${base}/art/shapes/textures`);
        for (const tex of backdropTextureFiles) {
          zip.file(`${base}/art/shapes/textures/${tex.name}.${tex.ext}`, tex.data);
          // One BeamNG Material entry per tile, referencing its satellite texture.
          shapeMaterials[tex.name] = {
            class: 'Material',
            name: tex.name,
            mapTo: tex.name,
            annotation: 'TERRAIN',
            Stages: [{
              diffuseMap: `levels/${levelName}/art/shapes/textures/${tex.name}.${tex.ext}`,
              diffuseColor: [1, 1, 1, 1],
            }],
            translucentBlendOp: 'None',
          };
        }
      } else {
        // No satellite textures available — use a flat earth-tone fallback.
        shapeMaterials.backdrop_terrain = {
          class: 'Material',
          name: 'backdrop_terrain',
          mapTo: 'backdrop_terrain',
          annotation: 'TERRAIN',
          Stages: [{ diffuseColor: [0.55, 0.5, 0.45, 1] }],
          translucentBlendOp: 'None',
        };
      }
    }
    zip.file(`${base}/art/shapes/main.materials.json`, JSON.stringify(shapeMaterials, null, 2));
  }

  // ── art/terrains/terrain.png ───────────────────────────────────────────────
  zip.file(`${base}/art/terrains/terrain.png`, texBlob);
  texBlob = null;

  // ── art/terrains/ PBR textures (when OSM material painting is enabled) ─────
  if (pbrResult?.textureFiles?.length) {
    for (const { path, blob } of pbrResult.textureFiles) {
      zip.file(`${base}/art/terrains/${path}`, blob);
    }
  }

  // ── art/terrains/main.materials.json ──────────────────────────────────────
  // When PBR materials are active, write all material definitions from the
  // OSM painter (DefaultMaterial satellite base + PBR overlays).
  // Otherwise, fall back to a single DefaultMaterial covering the whole terrain.
  const terrainMaterialDefs = pbrResult?.materialDefs ?? {
    DefaultMaterial: {
      class: 'TerrainMaterial',
      internalName: 'DefaultMaterial',
      diffuseMap: `levels/${levelName}/art/terrains/terrain.png`,
      diffuseSize: size,
      groundmodelName: 'GROUNDMODEL_ASPHALT1',
    },
  };
  zip.file(`${base}/art/terrains/main.materials.json`, JSON.stringify(terrainMaterialDefs, null, 2));

  // ── theTerrain.terrain.json — update materials list to match .ter contents ─
  const terrainMaterialNames = pbrResult?.materialNames ?? ['DefaultMaterial'];
  const heightMapSize = size * size;
  zip.file(`${base}/theTerrain.terrain.json`, JSON.stringify({
    binaryFormat: 'version(char), size(unsigned int), heightMap(heightMapSize * heightMapItemSize), layerMap(layerMapSize * layerMapItemSize), layerTextureMap(layerMapSize * layerMapItemSize), materialNames',
    datafile: `/levels/${levelName}/theTerrain.ter`,
    heightMapItemSize: 2,
    heightMapSize,
    heightmapImage: `/levels/${levelName}/theTerrain.terrainheightmap.png`,
    layerMapItemSize: 1,
    layerMapSize: heightMapSize,
    materials: terrainMaterialNames,
    size,
    version: 9,
  }, null, 2));

  // ── art/shapes/google_tiles_NN/ (route mode: one folder per chunk tile) ────
  // Route mode has no OSM, so the single-tile art/shapes block above is skipped;
  // write each chunk's pre-assembled tile shape + atlas + materials here. Layout
  // and material shape mirror the single google_tiles folder exactly.
  if (routeTilePieces?.length) {
    zip.folder(`${base}/art/shapes`);
    for (const piece of routeTilePieces) {
      const dir = `art/shapes/${piece.name}`;
      zip.folder(`${base}/${dir}`);
      if (piece.daeBlob) {
        zip.file(`${base}/${dir}/google_tiles.dae`, piece.daeBlob);
      } else if (piece.glbBlob) {
        // Blender bridge was unavailable — ship the GLB + the conversion script.
        zip.file(`${base}/${dir}/google_tiles.glb`, piece.glbBlob);
        zip.file(`${base}/${dir}/beamng_glb_to_dae.py`, beamngGlbToDaeScript);
      }
      const mats = {};
      if (piece.textureFiles?.length) {
        zip.folder(`${base}/${dir}/textures`);
        for (const tex of piece.textureFiles) {
          zip.file(`${base}/${dir}/textures/${tex.name}.${tex.ext}`, tex.data);
          mats[tex.name] = {
            name: tex.name,
            mapTo: tex.name,
            class: 'Material',
            Stages: [
              { colorMap: `levels/${levelName}/${dir}/textures/${tex.name}.${tex.ext}` },
              {}, {}, {},
            ],
            translucentBlendOp: 'None',
          };
        }
      }
      zip.file(`${base}/${dir}/main.materials.json`, JSON.stringify(mats, null, 2));
    }
  }
}
