/** @layer core */
// Static BeamNG flavor (target-level) catalog (refactor doc 06 step 10).
// Verbatim data drained from beamngFlavorCatalog.js — no logic.
import { WATER_PROFILES } from './waterProfiles.js';

export const BEAMNG_FLAVORS = [
  {
    id: 'italy',
    label: 'Italy',
    levelName: 'italy',
    environmentProfile: { globalEnvironmentMap: 'cubemap_italy_reflection' },
    waterProfile: WATER_PROFILES.italy,
    assetSetIds: ['italy', 'automation_test_track', 'east_coast'],
    terrainLevelFallbacks: ['italy', 'east_coast_usa', 'jungle_rock_island', 'Utah'],
  },
  {
    id: 'utah',
    label: 'Utah',
    levelName: 'Utah',
    environmentProfile: { globalEnvironmentMap: 'cubemap_utah_reflection' },
    waterProfile: WATER_PROFILES.utah,
    assetSetIds: ['utah', 'small_island', 'johnson_valley', 'east_coast'],
    terrainLevelFallbacks: ['Utah', 'johnson_valley', 'small_island', 'east_coast_usa'],
  },
  {
    id: 'automation_test_track',
    label: 'Automation Test Track',
    levelName: 'automation_test_track',
    environmentProfile: { globalEnvironmentMap: 'cubemap_automation_reflection' },
    waterProfile: WATER_PROFILES.automation_test_track,
    assetSetIds: ['automation_test_track', 'italy', 'east_coast'],
    terrainLevelFallbacks: ['automation_test_track', 'italy', 'east_coast_usa'],
  },
  {
    id: 'driver_training',
    label: 'Driver Training',
    levelName: 'driver_training',
    environmentProfile: { globalEnvironmentMap: 'cubemap_driver_training_reflection' },
    waterProfile: WATER_PROFILES.driver_training,
    assetSetIds: ['east_coast', 'automation_test_track', 'italy'],
    terrainLevelFallbacks: ['driver_training', 'east_coast_usa', 'automation_test_track', 'italy'],
  },
  {
    id: 'east_coast_usa',
    label: 'East Coast USA',
    levelName: 'east_coast_usa',
    environmentProfile: { globalEnvironmentMap: 'cubemap_eca_reflection' },
    waterProfile: WATER_PROFILES.east_coast_usa,
    assetSetIds: ['east_coast', 'west_coast', 'italy'],
    terrainLevelFallbacks: ['east_coast_usa', 'west_coast_usa', 'italy', 'Utah'],
  },
  {
    id: 'gridmap_v2',
    label: 'Gridmap V2',
    levelName: 'gridmap_v2',
    environmentProfile: { globalEnvironmentMap: 'cubemap_ocean_reflection' },
    waterProfile: WATER_PROFILES.gridmap_v2,
    assetSetIds: ['east_coast', 'utah'],
    terrainLevelFallbacks: ['gridmap_v2', 'east_coast_usa', 'Utah', 'italy'],
  },
  {
    id: 'hirochi_raceway',
    label: 'Hirochi Raceway',
    levelName: 'hirochi_raceway',
    environmentProfile: { globalEnvironmentMap: 'cubemap_hirochi_raceway_reflection' },
    waterProfile: WATER_PROFILES.hirochi_raceway,
    assetSetIds: ['hirochi_raceway', 'east_coast', 'italy'],
    terrainLevelFallbacks: ['hirochi_raceway', 'east_coast_usa', 'italy', 'Utah'],
  },
  {
    id: 'industrial',
    label: 'Industrial',
    levelName: 'Industrial',
    environmentProfile: { globalEnvironmentMap: 'cubemap_industrial_reflection' },
    waterProfile: WATER_PROFILES.Industrial,
    assetSetIds: ['industrial', 'automation_test_track', 'east_coast', 'italy'],
    terrainLevelFallbacks: ['Industrial', 'east_coast_usa', 'italy', 'automation_test_track'],
  },
  {
    id: 'johnson_valley',
    label: 'Johnson Valley',
    levelName: 'johnson_valley',
    environmentProfile: { globalEnvironmentMap: 'cubemap_johnson_valley_reflection' },
    waterProfile: WATER_PROFILES.johnson_valley,
    assetSetIds: ['johnson_valley', 'utah', 'west_coast'],
    terrainLevelFallbacks: ['johnson_valley', 'Utah', 'west_coast_usa', 'east_coast_usa'],
  },
  {
    id: 'jungle_rock_island',
    label: 'Jungle Rock Island',
    levelName: 'jungle_rock_island',
    environmentProfile: { globalEnvironmentMap: 'cubemap_jungle_reflection' },
    waterProfile: WATER_PROFILES.jungle_rock_island,
    assetSetIds: ['jungle', 'italy', 'johnson_valley'],
    terrainLevelFallbacks: ['jungle_rock_island', 'italy', 'johnson_valley', 'east_coast_usa'],
  },
  {
    id: 'small_island',
    label: 'Small Island',
    levelName: 'small_island',
    environmentProfile: { globalEnvironmentMap: 'cubemap_small_island_reflection' },
    waterProfile: WATER_PROFILES.small_island,
    assetSetIds: ['small_island', 'utah', 'jungle'],
    terrainLevelFallbacks: ['small_island', 'Utah', 'italy', 'jungle_rock_island'],
  },
  {
    id: 'west_coast_usa',
    label: 'West Coast USA',
    levelName: 'west_coast_usa',
    environmentProfile: { globalEnvironmentMap: 'cubemap_wca_reflection' },
    waterProfile: WATER_PROFILES.west_coast_usa,
    assetSetIds: ['west_coast', 'east_coast', 'johnson_valley'],
    terrainLevelFallbacks: ['west_coast_usa', 'east_coast_usa', 'johnson_valley', 'italy'],
  },
];
