/** @layer core */
// BeamNG forest/asset-set data, part A (refactor doc 06 step 10).
// Verbatim slice of ASSET_SETS from beamngFlavorCatalog.js — no logic.
import {
  ITALY_GROUNDCOVER_MATERIAL,
  UTAH_GROUNDCOVER_MATERIAL,
  EAST_COAST_GROUNDCOVER_MATERIAL,
} from './groundCoverMaterials.js';

export const ASSET_SETS_A = {
  italy: {
    managedItemTemplates: {
      cypress_tree: {
        name: 'cypress_tree',
        internalName: 'cypress_tree',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        detailAmp: 0.0799999982,
        detailFreq: 1.5,
        mass: 10,
        radius: 0.800000012,
        rigidity: 10.1999998,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/cypress_tree.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0500000007,
        windScale: 0.300000012,
      },
      holm_oak_city_small: {
        name: 'holm_oak_city_small',
        internalName: 'holm_oak_city_small',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        detailAmp: 0.200000003,
        detailFreq: 0.5,
        mass: 10,
        radius: 0.699999988,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/holm_oak_city_small.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0500000007,
        windScale: 0.5,
      },
      maritime_pine_tree: {
        name: 'maritime_pine_tree',
        internalName: 'maritime_pine_tree',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        dampingCoefficient: 3,
        detailAmp: 0.119999997,
        detailFreq: 1.5,
        mass: 10,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/maritime_pine.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0700000003,
        windScale: 0.5,
      },
      olive_tree: {
        name: 'olive_tree',
        internalName: 'olive_tree',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        dampingCoefficient: 3,
        detailAmp: 5,
        detailFreq: 0.100000001,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/olive.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0500000007,
        windScale: 0.5,
      },
      italy_palm_1: {
        name: 'italy_palm_1',
        internalName: 'italy_palm_1',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        dampingCoefficient: 3,
        detailAmp: 0.300000012,
        detailFreq: 0.5,
        dynamicCubemap: '0',
        planarReflection: '0',
        rigidity: 20,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/italy_palm_1.dae',
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
        trunkBendScale: 0.0299999993,
        windScale: 0.5,
      },
      generibush: {
        name: 'generibush',
        internalName: 'generibush',
        class: 'ForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        dampingCoefficient: 3,
        detailAmp: 5,
        detailFreq: 0.0700000003,
        dynamicCubemap: '0',
        planarReflection: '0',
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/generibush.dae',
        snapRotationToTerrain: true,
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
        trunkBendScale: 0.0500000007,
        windScale: 0.5,
      },
      holm_oak_bush_huge: {
        name: 'holm_oak_bush_huge',
        internalName: 'holm_oak_bush_huge',
        class: 'ForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.100000001,
        detailAmp: 0.200000003,
        detailFreq: 0.5,
        mass: 10,
        shapeFile: 'levels/italy/art/shapes/trees/trees_italy/holm_oak_bush_huge.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0500000007,
        windScale: 0.5,
      },
      italy_rockface_boulder_1: {
        name: 'italy_rockface_boulder_1',
        internalName: 'italy_rockface_boulder_1',
        class: 'ForestItemData',
        dampingCoefficient: 3,
        dynamicCubemap: '0',
        planarReflection: '0',
        radius: 0.699999988,
        shapeFile: 'levels/italy/art/shapes/rocks/italy_rockface_boulder_1.dae',
        snapRotationToTerrain: true,
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
      },
      italy_rockface_boulder_2: {
        name: 'italy_rockface_boulder_2',
        internalName: 'italy_rockface_boulder_2',
        class: 'ForestItemData',
        dampingCoefficient: 3,
        dynamicCubemap: '0',
        planarReflection: '0',
        radius: 0.699999988,
        shapeFile: 'levels/italy/art/shapes/rocks/italy_rockface_boulder_2.dae',
        snapRotationToTerrain: true,
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
      },
      italy_rockface_boulder_3: {
        name: 'italy_rockface_boulder_3',
        internalName: 'italy_rockface_boulder_3',
        class: 'ForestItemData',
        dampingCoefficient: 3,
        dynamicCubemap: '0',
        planarReflection: '0',
        radius: 0.699999988,
        shapeFile: 'levels/italy/art/shapes/rocks/italy_rockface_boulder_3.dae',
        snapRotationToTerrain: true,
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
      },
      italy_rockface_boulder_4: {
        name: 'italy_rockface_boulder_4',
        internalName: 'italy_rockface_boulder_4',
        class: 'ForestItemData',
        dampingCoefficient: 3,
        dynamicCubemap: '0',
        planarReflection: '0',
        radius: 0.699999988,
        shapeFile: 'levels/italy/art/shapes/rocks/italy_rockface_boulder_4.dae',
        snapRotationToTerrain: true,
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
      },
    },
    vegetationSelectors: {
      default: 'holm_oak_city_small',
      needle: 'maritime_pine_tree',
      palm: 'italy_palm_1',
      olive: 'olive_tree',
      cypress: 'cypress_tree',
      bush: 'generibush',
      hedgeBush: 'holm_oak_bush_huge',
    },
    rockCandidates: [
      'italy_rockface_boulder_1',
      'italy_rockface_boulder_2',
      'italy_rockface_boulder_3',
      'italy_rockface_boulder_4',
    ],
    groundCover: {
      materialName: 'GrassMiddle',
      materialDef: ITALY_GROUNDCOVER_MATERIAL,
      terrainLayer: 'Grass',
    },
  },
  utah: {
    managedItemTemplates: {
      Juniper_tree_01: {
        name: 'Juniper_tree_01',
        internalName: 'Juniper_tree_01',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.0500000007,
        detailAmp: 0.100000001,
        detailFreq: 1,
        mass: 20,
        shapeFile: '/levels/Utah/art/shapes/trees/Juniper/Juniper_tree_01.dae',
        trunkBendScale: 0.00400000019,
        windScale: 0.400000006,
      },
      Juniper_bush_large_01: {
        name: 'Juniper_bush_large_01',
        internalName: 'Juniper_bush_large_01',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        dampingCoefficient: 0.00400000019,
        detailAmp: 0.100000001,
        detailFreq: 1,
        mass: 4,
        radius: 0.5,
        rigidity: 20,
        shapeFile: '/levels/Utah/art/shapes/trees/Juniper/Juniper_bush_large_01.dae',
        trunkBendScale: 0.00400000019,
        windScale: 0.400000006,
      },
      utah_rock_small_a: {
        name: 'utah_rock_small_a',
        internalName: 'utah_rock_small_a',
        class: 'TSForestItemData',
        radius: 0.5,
        shapeFile: 'levels/Utah/art/shapes/rocks/utah_rock_small_a.dae',
      },
    },
    vegetationSelectors: {
      default: 'Juniper_tree_01',
      needle: 'Juniper_tree_01',
      bush: 'Juniper_bush_large_01',
      hedgeBush: 'Juniper_bush_large_01',
    },
    rockCandidates: ['utah_rock_small_a'],
    groundCover: {
      materialName: 'dry_grass',
      materialDef: UTAH_GROUNDCOVER_MATERIAL,
      terrainLayer: 'Grass',
    },
  },
  small_island: {
    managedItemTemplates: {
      Juniper_tree_01: {
        name: 'Juniper_tree_01',
        internalName: 'Juniper_tree_01',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.0500000007,
        detailAmp: 0.100000001,
        detailFreq: 1,
        mass: 20,
        shapeFile: '/levels/small_island/art/shapes/trees/Juniper/Juniper_tree_01.dae',
        trunkBendScale: 0.00400000019,
        windScale: 0.400000006,
      },
      Juniper_bush_large_01: {
        name: 'Juniper_bush_large_01',
        internalName: 'Juniper_bush_large_01',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        dampingCoefficient: 0.00400000019,
        detailAmp: 0.100000001,
        detailFreq: 1,
        mass: 4,
        radius: 0.5,
        rigidity: 20,
        shapeFile: '/levels/small_island/art/shapes/trees/Juniper/Juniper_bush_large_01.dae',
        trunkBendScale: 0.00400000019,
        windScale: 0.400000006,
      },
    },
    vegetationSelectors: {
      default: 'Juniper_tree_01',
      needle: 'Juniper_tree_01',
      bush: 'Juniper_bush_large_01',
      hedgeBush: 'Juniper_bush_large_01',
    },
    rockCandidates: [],
  },
  east_coast: {
    managedItemTemplates: {
      tree_aspen_small_a: {
        name: 'tree_aspen_small_a',
        internalName: 'tree_aspen_small_a',
        class: 'TSForestItemData',
        branchAmp: 0.0299999993,
        detailAmp: 0.200000003,
        detailFreq: 4,
        mass: 20,
        rigidity: 17,
        shapeFile: 'levels/east_coast_usa/art/shapes/trees/trees_aspen/tree_aspen_small_a.dae',
        trunkBendScale: 0.100000001,
        windScale: 0.400000006,
      },
      tree_beech_bush_a: {
        name: 'tree_beech_bush_a',
        internalName: 'tree_beech_bush_a',
        class: 'TSForestItemData',
        branchAmp: 0.0199999996,
        dampingCoefficient: 0.400000006,
        detailAmp: 0.300000012,
        detailFreq: 4,
        mass: 1,
        radius: 0.5,
        rigidity: 11,
        shapeFile: 'levels/east_coast_usa/art/shapes/trees/trees_beech/tree_beech_bush_a.dae',
        tightnessCoefficient: 4,
        trunkBendScale: 0.0500000007,
        windScale: 0.400000006,
      },
      eca_rock_small: {
        name: 'eca_rock_small',
        internalName: 'eca_rock_small',
        class: 'TSForestItemData',
        annotation: 'ROCK',
        radius: 0.100000001,
        shapeFile: '/levels/east_coast_usa/art/shapes/rocks/eca_rock_small.dae',
      },
    },
    vegetationSelectors: {
      default: 'tree_aspen_small_a',
      needle: 'tree_aspen_small_a',
      bush: 'tree_beech_bush_a',
      hedgeBush: 'tree_beech_bush_a',
    },
    rockCandidates: ['eca_rock_small'],
    groundCover: {
      materialName: 'BNGGrass',
      materialDef: EAST_COAST_GROUNDCOVER_MATERIAL,
      terrainLayer: 'Grass',
    },
  },
};
