/** @layer core */
// BeamNG forest/asset-set data, part B (refactor doc 06 step 10).
// Verbatim slice of ASSET_SETS from beamngFlavorCatalog.js — no logic.
import {
  JOHNSON_VALLEY_GROUNDCOVER_MATERIAL,
  JUNGLE_GROUNDCOVER_MATERIAL,
} from './groundCoverMaterials.js';

export const ASSET_SETS_B = {
  west_coast: {
    managedItemTemplates: {
      deserttree_bush_medium: {
        name: 'deserttree_bush_medium',
        internalName: 'deserttree_bush_medium',
        class: 'TSForestItemData',
        branchAmp: 0.00499999989,
        detailAmp: 0.0199999996,
        detailFreq: 0.699999988,
        mass: 1,
        order_simset: '7564389',
        radius: 0.5,
        shapeFile: 'levels/west_coast_usa/art/shapes/trees/deserttrees/deserttree_bush_medium.dae',
        trunkBendScale: 0.00200000079,
        windScale: 0.5,
      },
      eca_rock_small: {
        name: 'eca_rock_small',
        internalName: 'eca_rock_small',
        class: 'TSForestItemData',
        shapeFile: '/levels/west_coast_usa/art/shapes/rocks/eca_rock_small.dae',
      },
    },
    vegetationSelectors: {
      bush: 'deserttree_bush_medium',
      hedgeBush: 'deserttree_bush_medium',
    },
    rockCandidates: ['eca_rock_small'],
  },
  johnson_valley: {
    managedItemTemplates: {
      deserttree_bush_medium: {
        name: 'deserttree_bush_medium',
        internalName: 'deserttree_bush_medium',
        class: 'TSForestItemData',
        branchAmp: 0.00499999989,
        detailAmp: 0.0199999996,
        detailFreq: 0.699999988,
        mass: 1,
        order_simset: '7564389',
        radius: 0.5,
        shapeFile: 'levels/johnson_valley/art/shapes/trees/deserttrees/deserttree_bush_medium.dae',
        trunkBendScale: 0.00200000079,
        windScale: 0.5,
      },
      desert_rocks_small_01: {
        name: 'desert_rocks_small_01',
        internalName: 'desert_rocks_small_01',
        class: 'TSForestItemData',
        dampingCoefficient: 3,
        dynamicCubemap: '0',
        order_simset: '1030236933',
        planarReflection: '0',
        radius: 0.600000024,
        shadowNullDetailSize: 40,
        shapeFile: 'levels/johnson_valley/art/shapes/rocks/s_rocks_desert_small_01.dae',
        tightnessCoefficient: 1,
        translucentBlendOp: 'LerpAlpha',
      },
    },
    vegetationSelectors: {
      default: 'deserttree_bush_medium',
      needle: 'deserttree_bush_medium',
      bush: 'deserttree_bush_medium',
      hedgeBush: 'deserttree_bush_medium',
    },
    rockCandidates: ['desert_rocks_small_01'],
    groundCover: {
      materialName: 'dry_grass',
      materialDef: JOHNSON_VALLEY_GROUNDCOVER_MATERIAL,
      terrainLayer: 'Grass',
    },
  },
  jungle: {
    managedItemTemplates: {
      deadpalm_01: {
        name: 'deadpalm_01',
        internalName: 'deadpalm_01',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        order_simset: '524',
        radius: 0.200000003,
        shapeFile: '/levels/jungle_rock_island/art/shapes/trees/trees_palm/deadpalm_01.dae',
      },
      grass_field_sml: {
        name: 'grass_field_sml',
        internalName: 'grass_field_sml',
        class: 'TSForestItemData',
        collidable: false,
        detailAmp: 0.5,
        detailFreq: 0.5,
        radius: 0.200000003,
        shapeFile: 'levels/jungle_rock_island/art/shapes/groundcover/grass_field_sml.dae',
        tightnessCoefficient: 4,
        trunkBendScale: 0.100000001,
        windScale: 0.5,
      },
      pac_rock_small_1: {
        name: 'pac_rock_small_1',
        internalName: 'pac_rock_small_1',
        class: 'TSForestItemData',
        annotation: 'ROCK',
        order_simset: '3276856',
        radius: 0.200000003,
        shapeFile: '/levels/jungle_rock_island/art/shapes/rocks/pac_rock_small_1.dae',
      },
    },
    vegetationSelectors: {
      default: 'deadpalm_01',
      palm: 'deadpalm_01',
      bush: 'grass_field_sml',
      hedgeBush: 'grass_field_sml',
    },
    rockCandidates: ['pac_rock_small_1'],
    groundCover: {
      materialName: 'BNG_Grass_03',
      materialDef: JUNGLE_GROUNDCOVER_MATERIAL,
      terrainLayer: 'Grass',
    },
  },
  industrial: {
    managedItemTemplates: {
      cork_oak_bush_large: {
        name: 'cork_oak_bush_large',
        internalName: 'cork_oak_bush_large',
        class: 'TSForestItemData',
        branchAmp: 0.100000001,
        dampingCoefficient: 3,
        detailAmp: 0.5,
        detailFreq: 0.5,
        mass: 4,
        radius: 0.5,
        rigidity: 20,
        shapeFile: 'levels/industrial/art/shapes/trees/trees_italy/cork_oak_bush_large.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.0500000007,
        windScale: 0.5,
      },
      DRI_rock_a: {
        name: 'DRI_rock_a',
        internalName: 'DRI_rock_a',
        class: 'TSForestItemData',
        shapeFile: 'levels/industrial/art/shapes/rocks/DRI_rock_a.dae',
      },
    },
    vegetationSelectors: {
      bush: 'cork_oak_bush_large',
      hedgeBush: 'cork_oak_bush_large',
    },
    rockCandidates: ['DRI_rock_a'],
  },
  automation_test_track: {
    managedItemTemplates: {
      cork_oak_large_1: {
        name: 'cork_oak_large_1',
        internalName: 'cork_oak_large_1',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.00999999978,
        dampingCoefficient: 0.200000003,
        detailAmp: 0.0500000007,
        detailFreq: 0.5,
        mass: 20,
        shapeFile: '/levels/automation_test_track/art/shapes/trees/trees_cork_oak/cork_oak_large_1.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.00100000005,
        windScale: 0.300000012,
      },
      cork_oak_bush_large: {
        name: 'cork_oak_bush_large',
        internalName: 'cork_oak_bush_large',
        class: 'TSForestItemData',
        annotation: 'NATURE',
        branchAmp: 0.00999999978,
        dampingCoefficient: 0.200000003,
        detailAmp: 0.100000001,
        detailFreq: 0.5,
        mass: 2,
        shapeFile: '/levels/automation_test_track/art/shapes/trees/trees_cork_oak/cork_oak_bush_large.dae',
        tightnessCoefficient: 1,
        trunkBendScale: 0.00499999989,
        windScale: 0.5,
      },
      rocks_nz_jagged_medium_1: {
        name: 'rocks_nz_jagged_medium_1',
        internalName: 'rocks_nz_jagged_medium_1',
        class: 'TSForestItemData',
        radius: 0.300000012,
        shapeFile: 'levels/automation_test_track/art/shapes/rocks/s_rocks_nz_jagged_medium_1.dae',
      },
    },
    vegetationSelectors: {
      default: 'cork_oak_large_1',
      needle: 'cork_oak_large_1',
      bush: 'cork_oak_bush_large',
      hedgeBush: 'cork_oak_bush_large',
    },
    rockCandidates: ['rocks_nz_jagged_medium_1'],
  },
  hirochi_raceway: {
    managedItemTemplates: {
      cork_oak_bush_large: {
        name: 'cork_oak_bush_large',
        internalName: 'cork_oak_bush_large',
        class: 'TSForestItemData',
        shapeFile: 'levels/hirochi_raceway/art/shapes/trees/ECA_coast_bush/cork_oak_bush_large.dae',
      },
      eca_rock_small: {
        name: 'eca_rock_small',
        internalName: 'eca_rock_small',
        class: 'TSForestItemData',
        annotation: 'ROCK',
        radius: 0.100000001,
        shapeFile: '/levels/hirochi_raceway/art/shapes/rocks/eca_rock_small.dae',
      },
    },
    vegetationSelectors: {
      bush: 'cork_oak_bush_large',
      hedgeBush: 'cork_oak_bush_large',
    },
    rockCandidates: ['eca_rock_small'],
  },
};
