/** @layer core */
// Game-referenced BeamNG TerrainMaterial templates (refactor doc 06 step 10).
// Pure static data drained verbatim from osmTerrainMaterials.js. During export
// the detail/macro slots are kept intact and only the base slots are rewritten
// to point at the generated terrain base in the exported level.

// Index 0 = DefaultMaterial (satellite base), 1–7 = BeamNG-referenced materials.
const MATERIAL_NAMES_LIST = ['DefaultMaterial', 'Grass', 'Dirt', 'BeachSand', 'ROCK', 'asphalt', 'GRAVEL', 'Concrete'];

// Ordered name list for the .ter material slot array and external consumers.
export const MATERIAL_NAMES = MATERIAL_NAMES_LIST;
export { MATERIAL_NAMES_LIST };

export const REFERENCE_MATERIALS = [
  {
    internalName: 'Grass',
    template: {
      class: 'TerrainMaterial',
      annotation: 'GRASS',
      aoBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/east_coast_usa/art/terrains/t_grass1_ao.png',
      aoMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_grass_ao.png',
      aoMacroTexSize: 100,
      baseColorBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.319999993, 0],
      baseColorDetailTex: '/levels/east_coast_usa/art/terrains/t_grass1_b.png',
      baseColorMacroStrength: [0.100000001, 0.400000006],
      baseColorMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_grass_b.png',
      baseColorMacroTexSize: 100,
      detailDistAtten: [0, 0.899999976],
      detailDistances: [0, 0, 30, 60],
      groundmodelName: 'GRASS',
      heightBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/east_coast_usa/art/terrains/t_grass1_h.png',
      heightMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_grass_h.png',
      heightMacroTexSize: 100,
      macroDistAtten: [0.349999994, 0],
      macroDistances: [0, 0, 400, 8000],
      normalBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.600000024, 0],
      normalDetailTex: '/levels/east_coast_usa/art/terrains/t_grass1_nm.png',
      normalMacroStrength: [0.400000006, 0.600000024],
      normalMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_grass_nm.png',
      normalMacroTexSize: 100,
      roughnessBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.899999976, 0],
      roughnessDetailTex: '/levels/east_coast_usa/art/terrains/t_grass1_r.png',
      roughnessMacroStrength: [0.200000003, 0.5],
      roughnessMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_grass_r.png',
      roughnessMacroTexSize: 100,
    },
  },
  {
    internalName: 'Dirt',
    template: {
      class: 'TerrainMaterial',
      aoBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/gridmap_v2/art/terrains/t_dirt_loose_ao.png',
      aoMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_rocky_ao.png',
      baseColorBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.25, 0.25],
      baseColorDetailTex: '/levels/gridmap_v2/art/terrains/t_dirt_loose_b.png',
      baseColorMacroStrength: [0.100000001, 0.200000003],
      baseColorMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_rocky_b.png',
      detailDistance: 25,
      detailSize: 2,
      detailStrength: 0.5,
      diffuseSize: 50,
      groundmodelName: 'DIRT',
      heightBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/gridmap_v2/art/terrains/t_dirt_loose_h.png',
      heightMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_rocky_h.png',
      macroDistance: 1000,
      macroDistances: [0, 10, 100, 3000],
      macroMap: '/levels/gridmap_v2/art/terrains/macro_grass_d.color.png',
      macroSize: 40,
      macroStrength: 0.5,
      normalBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.699999988, 0.150000006],
      normalDetailTex: '/levels/gridmap_v2/art/terrains/t_dirt_loose_nm.png',
      normalMacroStrength: [0.300000012, 0.400000006],
      normalMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_rocky_nm.png',
      normalMap: '/levels/gridmap_v2/art/terrains/grass_n.normal.png',
      roughnessBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.300000012, 0.300000012],
      roughnessDetailTex: '/levels/gridmap_v2/art/terrains/t_dirt_loose_r.png',
      roughnessMacroStrength: [0.200000003, 0.699999988],
      roughnessMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_rocky_r.png',
    },
  },
  {
    internalName: 'BeachSand',
    template: {
      class: 'TerrainMaterial',
      annotation: 'SAND',
      aoBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/gridmap_v2/art/terrains/t_beachsand_ao.png',
      aoMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_clumpy_ao.png',
      baseColorBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.25, 0.25],
      baseColorDetailTex: '/levels/gridmap_v2/art/terrains/t_beachsand_b.png',
      baseColorMacroStrength: [0.0500000007, 0.100000001],
      baseColorMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_clumpy_b.png',
      detailDistance: 25,
      detailSize: 2,
      detailStrength: 0.5,
      diffuseSize: 50,
      groundmodelName: 'SAND',
      heightBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/gridmap_v2/art/terrains/t_beachsand_h.png',
      heightMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_clumpy_h.png',
      macroDistance: 1000,
      macroDistances: [0, 10, 100, 3000],
      macroSize: 40,
      macroStrength: 0.5,
      normalBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.699999988, 0.150000006],
      normalDetailTex: '/levels/gridmap_v2/art/terrains/t_beachsand_nm.png',
      normalMacroStrength: [0.25, 0.25],
      normalMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_clumpy_nm.png',
      roughnessBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.300000012, 0.300000012],
      roughnessDetailTex: '/levels/gridmap_v2/art/terrains/t_beachsand_r.png',
      roughnessMacroStrength: [0.150000006, 0.5],
      roughnessMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_clumpy_r.png',
    },
  },
  {
    internalName: 'ROCK',
    template: {
      class: 'TerrainMaterial',
      annotation: 'ROCK',
      aoBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/east_coast_usa/art/terrains/t_rock_eca_ao.png',
      aoMacroTex: '/levels/east_coast_usa/art/terrains/t_rocks_pac_ao.png',
      aoMacroTexSize: 10,
      baseColorBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.25, 0.25],
      baseColorDetailTex: '/levels/east_coast_usa/art/terrains/t_rock_eca_b.png',
      baseColorMacroStrength: [0.200000003, 0.300000012],
      baseColorMacroTex: '/levels/east_coast_usa/art/terrains/t_rocks_pac_b.png',
      baseColorMacroTexSize: 10,
      detailDistances: [0, 0, 15, 50],
      groundmodelName: 'ROCK',
      heightBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/east_coast_usa/art/terrains/t_rock_eca_h.png',
      heightMacroTex: '/levels/east_coast_usa/art/terrains/t_rocks_pac_h.png',
      heightMacroTexSize: 10,
      macroDistances: [0, 10, 100, 3000],
      normalBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.400000006, 0.150000006],
      normalDetailTex: '/levels/east_coast_usa/art/terrains/t_rock_eca_nm.png',
      normalMacroStrength: [0.800000012, 0.800000012],
      normalMacroTex: '/levels/east_coast_usa/art/terrains/t_rocks_pac_nm.png',
      normalMacroTexSize: 10,
      roughnessBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.300000012, 0.300000012],
      roughnessDetailTex: '/levels/east_coast_usa/art/terrains/t_rock_eca_r.png',
      roughnessMacroStrength: [0.150000006, 0.5],
      roughnessMacroTex: '/levels/east_coast_usa/art/terrains/t_rocks_pac_r.png',
      roughnessMacroTexSize: 10,
    },
  },
  {
    internalName: 'asphalt',
    template: {
      class: 'TerrainMaterial',
      annotation: 'ASPHALT',
      aoBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base02_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/east_coast_usa/art/terrains/t_asphalt_02_ao.png',
      aoMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_asphalt_ao.png',
      aoMacroTexSize: 80,
      baseColorBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base02_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.349999994, 0],
      baseColorDetailTex: '/levels/east_coast_usa/art/terrains/t_asphalt_02_b.png',
      baseColorMacroStrength: [0.300000012, 0.300000012],
      baseColorMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_asphalt_b.png',
      baseColorMacroTexSize: 80,
      groundmodelName: 'ASPHALT',
      heightBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base02_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/east_coast_usa/art/terrains/t_asphalt_02_h.png',
      heightMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_asphalt_h.png',
      heightMacroTexSize: 80,
      macroDistances: [0, 10, 100, 3000],
      normalBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base02_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.800000012, 0.200000003],
      normalDetailTex: '/levels/east_coast_usa/art/terrains/t_asphalt_02_nm.png',
      normalMacroStrength: [0.800000012, 0.800000012],
      normalMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_asphalt_nm.png',
      normalMacroTexSize: 80,
      roughnessBaseTex: '/levels/east_coast_usa/art/terrains/t_terrain_base02_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.699999988, 0.5],
      roughnessDetailTex: '/levels/east_coast_usa/art/terrains/t_asphalt_02_r.png',
      roughnessMacroStrength: [0.699999988, 0.699999988],
      roughnessMacroTex: '/levels/east_coast_usa/art/terrains/t_macro_asphalt_r.png',
      roughnessMacroTexSize: 80,
    },
  },
  {
    internalName: 'GRAVEL',
    template: {
      class: 'TerrainMaterial',
      aoBaseTex: '/levels/Utah/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/Utah/art/terrains/t_gravels_ao.png',
      aoDetailTexSize: 2,
      aoMacroTex: '/levels/Utah/art/terrains/t_macro_clumpy_ao.png',
      aoMacroTexSize: 10,
      baseColorBaseTex: '/levels/Utah/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.3, 0.3],
      baseColorDetailTex: '/levels/Utah/art/terrains/t_gravels_b.png',
      baseColorDetailTexSize: 2,
      baseColorMacroStrength: [0.1, 0.25],
      baseColorMacroTex: '/levels/Utah/art/terrains/t_macro_clumpy_b.png',
      baseColorMacroTexSize: 10,
      detailDistAtten: [1, 1],
      detailDistances: [0, 0, 50, 100],
      groundmodelName: 'GRAVEL',
      heightBaseTex: '/levels/Utah/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/Utah/art/terrains/t_gravels_h.png',
      heightDetailTexSize: 2,
      heightMacroTex: '/levels/Utah/art/terrains/t_macro_clumpy_h.png',
      heightMacroTexSize: 10,
      macroDistAtten: [0, 1],
      macroDistances: [0, 10, 100, 3000],
      normalBaseTex: '/levels/Utah/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.4, 0.15],
      normalDetailTex: '/levels/Utah/art/terrains/t_gravels_nm.png',
      normalDetailTexSize: 2,
      normalMacroStrength: [0.1, 0.7],
      normalMacroTex: '/levels/Utah/art/terrains/t_macro_clumpy_nm.png',
      normalMacroTexSize: 10,
      roughnessBaseTex: '/levels/Utah/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.35, 0.35],
      roughnessDetailTex: '/levels/Utah/art/terrains/t_gravels_r.png',
      roughnessDetailTexSize: 2,
      roughnessMacroStrength: [0.15, 0.5],
      roughnessMacroTex: '/levels/Utah/art/terrains/t_macro_clumpy_r.png',
      roughnessMacroTexSize: 10,
    },
  },
  {
    internalName: 'Concrete',
    template: {
      class: 'TerrainMaterial',
      annotation: 'ASPHALT',
      aoBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_ao.png',
      aoBaseTexSize: 2048,
      aoDetailTex: '/levels/gridmap_v2/art/terrains/t_concrete_gm_ao.png',
      aoMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_holes_ao.png',
      aoMacroTexSize: 40,
      baseColorBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_b.png',
      baseColorBaseTexSize: 2048,
      baseColorDetailStrength: [0.25, 0.25],
      baseColorDetailTex: '/levels/gridmap_v2/art/terrains/t_concrete_gm_b.png',
      baseColorMacroStrength: [0.100000001, 0.100000001],
      baseColorMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_holes_b.png',
      baseColorMacroTexSize: 40,
      detailDistance: 25,
      detailSize: 2,
      detailStrength: 0.5,
      diffuseSize: 50,
      groundmodelName: 'ASPHALT',
      heightBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_h.png',
      heightBaseTexSize: 2048,
      heightDetailTex: '/levels/gridmap_v2/art/terrains/t_concrete_gm_h.png',
      heightMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_holes_h.png',
      heightMacroTexSize: 40,
      macroDistance: 1000,
      macroDistances: [0, 10, 100, 3000],
      macroSize: 40,
      macroStrength: 0.5,
      normalBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_nm.png',
      normalBaseTexSize: 2048,
      normalDetailStrength: [0.699999988, 0.150000006],
      normalDetailTex: '/levels/gridmap_v2/art/terrains/t_concrete_gm_nm.png',
      normalMacroStrength: [0.100000001, 0.100000001],
      normalMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_holes_nm.png',
      normalMacroTexSize: 40,
      roughnessBaseTex: '/levels/gridmap_v2/art/terrains/t_terrain_base_r.png',
      roughnessBaseTexSize: 2048,
      roughnessDetailStrength: [0.600000024, 0.600000024],
      roughnessDetailTex: '/levels/gridmap_v2/art/terrains/t_concrete_gm_r.png',
      roughnessMacroStrength: [0.150000006, 0.5],
      roughnessMacroTex: '/levels/gridmap_v2/art/terrains/t_macro_holes_r.png',
      roughnessMacroTexSize: 40,
    },
  },
];
