/** @layer core */
// Static BeamNG per-level water/river texture profiles (refactor doc 06 step 10).
// Verbatim data drained from beamngFlavorCatalog.js — no logic.

export const WATER_PROFILES = {
  italy: {
    waterCubemap: 'cubemap_italy_reflection',
    waterDepthGradientTex: '/levels/italy/art/water/depthcolor_ramp_italy_muddy.png',
    waterFoamTex: 'levels/italy/art/water/foam2.dds',
    waterRippleTex: '/levels/italy/art/water/ripple.dds',
    riverCubemap: 'cubemap_ocean_reflection',
    riverDepthGradientTex: 'levels/italy/art/water/depthcolor_ramp_italy_rivers.png',
    riverRippleTex: 'levels/italy/art/water/ripple3.dds',
  },
  utah: {
    waterCubemap: 'cubemap_utah_reflection',
    waterDepthGradientTex: '/levels/Utah/art/water/depthcolor_ramp.png',
    waterFoamTex: 'levels/Utah/art/water/foam.dds',
    waterRippleTex: '/levels/Utah/art/water/ripple.dds',
    riverCubemap: 'cubemap_road_sky_reflection',
    riverDepthGradientTex: 'levels/Utah/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/Utah/art/water/ripple4.dds',
  },
  east_coast_usa: {
    waterCubemap: 'cubemap_eca_reflection',
    waterDepthGradientTex: '/levels/east_coast_usa/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/east_coast_usa/art/water/foam.dds',
    waterRippleTex: '/levels/east_coast_usa/art/water/ripple.dds',
    riverCubemap: 'cubemap_river_reflection',
    riverDepthGradientTex: 'levels/east_coast_usa/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/east_coast_usa/art/water/ripple3.dds',
  },
  west_coast_usa: {
    waterCubemap: 'cubemap_wca_reflection',
    waterDepthGradientTex: '/levels/east_coast_usa/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/east_coast_usa/art/water/foam.dds',
    waterRippleTex: '/levels/west_coast_usa/art/water/ripple4.dds',
    riverCubemap: 'cubemap_wca_reflection',
    riverDepthGradientTex: 'levels/east_coast_usa/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/east_coast_usa/art/water/ripple3.dds',
  },
  johnson_valley: {
    waterCubemap: 'cubemap_johnson_valley_reflection',
    waterDepthGradientTex: '/levels/johnson_valley/art/water/depthcolor_ramp_tropical_2.png',
    waterFoamTex: 'levels/johnson_valley/art/water/foam.dds',
    waterRippleTex: '/levels/johnson_valley/art/water/ripple.dds',
    riverCubemap: 'cubemap_road_sky_reflection',
    riverDepthGradientTex: 'levels/johnson_valley/art/water/depthcolor_ramp_tropical.png',
    riverRippleTex: 'levels/johnson_valley/art/water/ripple3.dds',
  },
  jungle_rock_island: {
    waterCubemap: 'cubemap_jungle_reflection',
    waterDepthGradientTex: '/levels/jungle_rock_island/art/water/depthcolor_ramp_tropical_2.png',
    waterFoamTex: 'levels/jungle_rock_island/art/water/foam.dds',
    waterRippleTex: '/levels/jungle_rock_island/art/water/ripple.dds',
    riverCubemap: 'cubemap_river_reflection',
    riverDepthGradientTex: 'levels/jungle_rock_island/art/water/depthcolor_ramp_jungle_river.png',
    riverRippleTex: 'levels/jungle_rock_island/art/water/ripple3.dds',
  },
  small_island: {
    waterCubemap: 'cubemap_small_island_reflection',
    waterDepthGradientTex: '/levels/italy/art/water/depthcolor_ramp_SI.png',
    waterFoamTex: 'levels/italy/art/water/foam.dds',
    waterRippleTex: '/levels/italy/art/water/ripple.dds',
    riverCubemap: 'cubemap_ocean_reflection',
    riverDepthGradientTex: 'levels/italy/art/water/depthcolor_ramp_SI.png',
    riverRippleTex: 'levels/italy/art/water/ripple3.dds',
  },
  Industrial: {
    waterCubemap: 'cubemap_industrial_reflection',
    waterDepthGradientTex: '/levels/Industrial/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/Industrial/art/water/foam.dds',
    waterRippleTex: '/levels/Industrial/art/water/ripple.dds',
    riverCubemap: 'cubemap_industrialriver_reflection',
    riverDepthGradientTex: 'levels/Industrial/art/water/depthcolor_ramp_colorful.png',
    riverRippleTex: 'levels/Industrial/art/water/ripple3.dds',
  },
  automation_test_track: {
    waterCubemap: 'cubemap_automation_reflection',
    waterDepthGradientTex: '/levels/automation_test_track/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/automation_test_track/art/water/foam.dds',
    waterRippleTex: '/levels/automation_test_track/art/water/ripple.dds',
    riverCubemap: 'cubemap_river_reflection',
    riverDepthGradientTex: 'levels/automation_test_track/art/water/depthcolor_ramp_jungle_river.png',
    riverRippleTex: 'levels/automation_test_track/art/water/ripple3.dds',
  },
  hirochi_raceway: {
    waterCubemap: 'cubemap_hirochi_raceway_reflection',
    waterDepthGradientTex: '/levels/east_coast_usa/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/east_coast_usa/art/water/foam.dds',
    waterRippleTex: '/levels/east_coast_usa/art/water/ripple.dds',
    riverCubemap: 'cubemap_ocean_reflection',
    riverDepthGradientTex: 'levels/east_coast_usa/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/east_coast_usa/art/water/ripple3.dds',
  },
  driver_training: {
    waterCubemap: 'cubemap_driver_training_reflection',
    waterDepthGradientTex: '/levels/east_coast_usa/art/water/depthcolor_ramp_mud1.png',
    waterFoamTex: 'levels/east_coast_usa/art/water/foam.dds',
    waterRippleTex: '/levels/east_coast_usa/art/water/ripple.dds',
    riverCubemap: 'cubemap_ocean_reflection',
    riverDepthGradientTex: 'levels/east_coast_usa/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/east_coast_usa/art/water/ripple3.dds',
  },
  gridmap_v2: {
    waterCubemap: 'cubemap_ocean_reflection',
    waterDepthGradientTex: '/levels/east_coast_usa/art/water/depthcolor_ramp_ocean.png',
    waterFoamTex: 'levels/east_coast_usa/art/water/foam.dds',
    waterRippleTex: 'levels/east_coast_usa/art/water/ripple.dds',
    riverCubemap: 'cubemap_ocean_reflection',
    riverDepthGradientTex: 'levels/east_coast_usa/art/water/depthcolor_ramp.png',
    riverRippleTex: 'levels/east_coast_usa/art/water/ripple3.dds',
  },
};
